// File generated by FlutterFire CLI.
// To re-generate this file, run:
//     flutterfire configure
//
// Replace every value marked with YOUR_... with the real values from:
//     Firebase Console → Project Settings → Your apps

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux – '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // Web
  // Firebase Console → Project Settings → Your apps → Web app → Config
  // ---------------------------------------------------------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg05ZSGYGXcEUNnrdvv14yksCNTvwSp4k',
    appId: '1:51648821502:web:ebd49d67b3b3ae431bcdaf',
    messagingSenderId: '51648821502',
    projectId: 'check-in-and-learning-mood-app',
    authDomain: 'check-in-and-learning-mood-app.firebaseapp.com',
    storageBucket: 'check-in-and-learning-mood-app.firebasestorage.app',
  );

  // ---------------------------------------------------------------------------
  // Android
  // Firebase Console → Project Settings → Your apps → Android app
  // Also copy google-services.json to android/app/
  // ---------------------------------------------------------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
  );

  // ---------------------------------------------------------------------------
  // iOS
  // Firebase Console → Project Settings → Your apps → iOS app
  // Also copy GoogleService-Info.plist to ios/Runner/
  // ---------------------------------------------------------------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.checkInAndLearningMoodApp',
  );

  // ---------------------------------------------------------------------------
  // macOS
  // Firebase Console → Project Settings → Your apps → iOS/macOS app
  // ---------------------------------------------------------------------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.checkInAndLearningMoodApp',
  );

  // ---------------------------------------------------------------------------
  // Windows
  // Firebase Console → Project Settings → Your apps → Web app
  // (Windows reuses a Web app configuration)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
  );
}
